const LS_RECORDS='gm_water_meter_records_v1';
const LS_METERS='gm_water_meter_meters_v1';
const defaultMeters=['Main Incoming Meter','Production Line Meter','Hot Wash Meter','Office / Domestic Meter'];
let records=JSON.parse(localStorage.getItem(LS_RECORDS)||'[]');
let meters=JSON.parse(localStorage.getItem(LS_METERS)||'null')||defaultMeters;
let editingId=null;
const $=id=>document.getElementById(id);
const today=()=>new Date().toISOString().slice(0,10);
function save(){localStorage.setItem(LS_RECORDS,JSON.stringify(records));localStorage.setItem(LS_METERS,JSON.stringify(meters));}
function uid(){return Date.now().toString(36)+Math.random().toString(36).slice(2,7)}
function num(v){return Number.parseFloat(v||0)||0}
function sortedRecords(list=records){return [...list].sort((a,b)=>(a.meterName+a.date+a.shift).localeCompare(b.meterName+b.date+b.shift));}
function calcUsageFor(record){const same=records.filter(r=>r.meterName===record.meterName&&r.id!==record.id).sort((a,b)=>(a.date+a.shift).localeCompare(b.date+b.shift));const prev=[...same].reverse().find(r=>(r.date+r.shift)<(record.date+record.shift));return prev?num(record.reading)-num(prev.reading):0;}
function renderMeters(){['meterName','summaryMeter'].forEach(id=>{const sel=$(id);const old=sel.value;sel.innerHTML=id==='summaryMeter'?'<option value="ALL">All</option>':'';meters.forEach(m=>{const o=document.createElement('option');o.value=m;o.textContent=m;sel.appendChild(o)});if([...sel.options].some(o=>o.value===old))sel.value=old;});$('meterList').innerHTML=meters.map(m=>`<span class="pill">${escapeHtml(m)} <button onclick="removeMeter('${encodeURIComponent(m)}')">×</button></span>`).join('');}
function escapeHtml(s){return String(s).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));}
window.removeMeter=(enc)=>{const m=decodeURIComponent(enc);if(records.some(r=>r.meterName===m)){alert('This meter already has records. Delete records first before removing it.');return}meters=meters.filter(x=>x!==m);save();renderMeters();}
function renderRecords(){const q=$('recordSearch').value.toLowerCase();const body=$('recordsTable').querySelector('tbody');const list=sortedRecords(records).filter(r=>JSON.stringify(r).toLowerCase().includes(q));body.innerHTML=list.map(r=>{const usage=calcUsageFor(r);return `<tr><td><input type="checkbox" class="rowChk" value="${r.id}"></td><td>${r.date}</td><td>${r.shift}</td><td>${escapeHtml(r.meterName)}</td><td>${num(r.reading).toFixed(2)}</td><td>${usage.toFixed(2)}</td><td>${escapeHtml(r.operator||'')}</td><td>${escapeHtml(r.remark||'')}</td><td><button class="secondary" onclick="editRecord('${r.id}')">Edit</button></td></tr>`}).join('')||'<tr><td colspan="9">No records yet.</td></tr>';}
window.editRecord=(id)=>{const r=records.find(x=>x.id===id);if(!r)return;editingId=id;$('entryDate').value=r.date;$('shift').value=r.shift;$('meterName').value=r.meterName;$('reading').value=r.reading;$('operator').value=r.operator||'';$('remark').value=r.remark||'';switchTab('daily');$('formMsg').textContent='Editing existing record';$('formMsg').className='msg ok';}
function clearForm(){editingId=null;$('entryDate').value=today();$('shift').value='Day';$('reading').value='';$('operator').value='';$('remark').value='';$('formMsg').textContent='';}
function showMsg(t,ok=true){$('formMsg').textContent=t;$('formMsg').className='msg '+(ok?'ok':'err');}
function saveEntry(){const r={id:editingId||uid(),date:$('entryDate').value,shift:$('shift').value,meterName:$('meterName').value,reading:num($('reading').value),operator:$('operator').value.trim(),remark:$('remark').value.trim()};if(!r.date||!r.meterName||!$('reading').value){showMsg('Date, meter and reading are required.',false);return}const dup=records.find(x=>x.id!==r.id&&x.date===r.date&&x.shift===r.shift&&x.meterName===r.meterName);if(dup&&!confirm('Duplicate same date + shift + meter. Save anyway?'))return;if(editingId){records=records.map(x=>x.id===editingId?r:x)}else{records.push(r)}save();renderRecords();renderSummary();runValidation();clearForm();showMsg('Record saved.');}
function renderSummary(){const from=$('summaryFrom').value||'0000-00-00';const to=$('summaryTo').value||'9999-99-99';const meter=$('summaryMeter').value;let list=records.filter(r=>r.date>=from&&r.date<=to&&(meter==='ALL'||r.meterName===meter));let issues=getIssues(list);let groups={};list.forEach(r=>{groups[r.meterName]=groups[r.meterName]||[];groups[r.meterName].push(r)});let totalUsage=0;const rows=Object.entries(groups).map(([m,arr])=>{arr.sort((a,b)=>(a.date+a.shift).localeCompare(b.date+b.shift));const first=num(arr[0].reading),last=num(arr[arr.length-1].reading),usage=Math.max(0,last-first);totalUsage+=usage;return `<tr><td>${escapeHtml(m)}</td><td>${arr.length}</td><td>${first.toFixed(2)}</td><td>${last.toFixed(2)}</td><td>${usage.toFixed(2)}</td></tr>`}).join('');$('summaryTable').querySelector('tbody').innerHTML=rows||'<tr><td colspan="5">No records.</td></tr>';$('totalUsage').textContent=totalUsage.toFixed(2);$('totalRecords').textContent=list.length;$('totalIssues').textContent=issues.length;}
function getIssues(list=records){const issues=[];const keyCount={};list.forEach(r=>{const k=`${r.date}|${r.meterName}|${r.shift}`;keyCount[k]=(keyCount[k]||0)+1;const u=calcUsageFor(r);if(u<0)issues.push({level:'err',date:r.date,meterName:r.meterName,shift:r.shift,issue:'Negative usage. Reading lower than previous reading.'});if(u===0)issues.push({level:'warn',date:r.date,meterName:r.meterName,shift:r.shift,issue:'Zero usage or first record.'});});Object.entries(keyCount).forEach(([k,c])=>{if(c>1){const [date,meterName,shift]=k.split('|');issues.push({level:'err',date,meterName,shift,issue:'Duplicate record for same date, shift and meter.'});}});const byDateMeter={};list.forEach(r=>{const k=`${r.date}|${r.meterName}`;byDateMeter[k]=byDateMeter[k]||new Set();byDateMeter[k].add(r.shift)});Object.entries(byDateMeter).forEach(([k,set])=>{if(!set.has('Day')||!set.has('Night')){const [date,meterName]=k.split('|');issues.push({level:'warn',date,meterName,shift:[...set].join('/'),issue:'Missing Day or Night shift record.'});}});return issues;}
function runValidation(){const body=$('validationTable').querySelector('tbody');const issues=getIssues();body.innerHTML=issues.map(i=>`<tr><td><span class="badge ${i.level}">${i.level==='err'?'ERROR':'CHECK'}</span></td><td>${i.date}</td><td>${escapeHtml(i.meterName)}</td><td>${escapeHtml(i.shift)}</td><td>${escapeHtml(i.issue)}</td></tr>`).join('')||'<tr><td colspan="5"><span class="badge ok">OK</span> No issue found.</td></tr>';renderSummary();}
function exportCsv(){const title='GM WATER METER REPORT';const cols=['Date','Shift','Meter','Reading','Usage','Operator','Remark'];const rows=sortedRecords(records).map(r=>[r.date,r.shift,r.meterName,num(r.reading).toFixed(2),calcUsageFor(r).toFixed(2),r.operator||'',r.remark||'']);const csv=[['','',title,'','','',''],cols,...rows].map(row=>row.map(v=>`"${String(v).replace(/"/g,'""')}"`).join(',')).join('\n');const blob=new Blob([csv],{type:'text/csv;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`GM_WATER_METER_REPORT_${today()}.csv`;a.click();URL.revokeObjectURL(a.href);}
function switchTab(name){document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.tab===name));document.querySelectorAll('.panel').forEach(p=>p.classList.toggle('active',p.id===name));if(name==='summary')renderSummary();if(name==='validation')runValidation();}
document.querySelectorAll('.tab').forEach(b=>b.addEventListener('click',()=>switchTab(b.dataset.tab)));
$('todayBtn').onclick=()=>$('entryDate').value=today();$('saveEntry').onclick=saveEntry;$('clearForm').onclick=clearForm;$('exportCsv').onclick=exportCsv;$('recordSearch').oninput=renderRecords;$('applySummary').onclick=renderSummary;$('runValidation').onclick=runValidation;$('addMeter').onclick=()=>{const v=$('newMeter').value.trim();if(!v)return;if(!meters.includes(v))meters.push(v);$('newMeter').value='';save();renderMeters();};$('deleteSelected').onclick=()=>{const ids=[...document.querySelectorAll('.rowChk:checked')].map(x=>x.value);if(!ids.length)return;if(confirm(`Delete ${ids.length} selected record(s)?`)){records=records.filter(r=>!ids.includes(r.id));save();renderRecords();renderSummary();runValidation();}};$('clearAllData').onclick=()=>{if(confirm('Clear ALL water meter records?')){records=[];save();renderRecords();renderSummary();runValidation();}};
let deferredPrompt;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('installBtn').classList.remove('hidden')});$('installBtn').onclick=async()=>{if(deferredPrompt){deferredPrompt.prompt();deferredPrompt=null;$('installBtn').classList.add('hidden')}};
if('serviceWorker' in navigator){navigator.serviceWorker.register('./sw.js').catch(()=>{});}renderMeters();clearForm();$('summaryFrom').value=today();$('summaryTo').value=today();renderRecords();renderSummary();runValidation();
