let state=loadState();
const shifts=['Day','Night'];
const $=id=>document.getElementById(id);
function ymNow(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`}
function daysInMonth(ym){const[y,m]=ym.split('-').map(Number);return new Date(y,m,0).getDate()}
function dateKey(ym,day,shift){return `${ym}-${String(day).padStart(2,'0')}|${shift}`}
function prettyDate(ym,day){const[y,m]=ym.split('-').map(Number);return `${day}/${m}/${y}`}
function monthLabel(ym){const[y,m]=ym.split('-').map(Number);return new Date(y,m-1,1).toLocaleString('en-GB',{month:'long',year:'numeric'})}
function ensureInputs(){['monthPicker','summaryMonth','validationMonth'].forEach(id=>$(id).value=$(id).value||ymNow())}
function rowsForMonth(ym){const rows=[];for(let d=1;d<=daysInMonth(ym);d++)for(const s of shifts)rows.push({day:d,shift:s,key:dateKey(ym,d,s)});return rows}
function getReading(key,meter){return state.readings[key]?.[meter]??''}
function setReading(key,meter,value){if(!state.readings[key])state.readings[key]={};if(value==='')delete state.readings[key][meter];else state.readings[key][meter]=Number(value);saveState()}
function previousReading(ym,rowIndex,meter){const rows=rowsForMonth(ym);for(let i=rowIndex-1;i>=0;i--){const v=getReading(rows[i].key,meter);if(v!==''&&!Number.isNaN(Number(v)))return Number(v)}return null}
function usageFor(ym,rowIndex,meter){const rows=rowsForMonth(ym);const cur=getReading(rows[rowIndex].key,meter);if(cur===''||Number.isNaN(Number(cur)))return '';const prev=previousReading(ym,rowIndex,meter);if(prev===null)return '';return Number(cur)-prev}
function renderSheet(){const ym=$('monthPicker').value;const rows=rowsForMonth(ym);let html=`<tr class="titleRow"><th colspan="${3+state.meters.length*2}">GM WATER METER REPORT - ${monthLabel(ym)}</th></tr>`;html+='<tr><th>Date</th><th>Shift</th>';state.meters.forEach(m=>{html+=`<th>${m}<br>Reading</th><th>${m}<br>Usage</th>`});html+='<th>Total Usage</th></tr>';rows.forEach((r,i)=>{let total=0,has=false;html+=`<tr><td class="dateCell">${prettyDate(ym,r.day)}</td><td class="${r.shift==='Day'?'shiftDay':'shiftNight'}">${r.shift}</td>`;state.meters.forEach(m=>{const val=getReading(r.key,m);const u=usageFor(ym,i,m);const cls=typeof u==='number'&&u<0?'usage bad':'usage';if(typeof u==='number'){total+=u;has=true}html+=`<td><input class="reading" type="number" inputmode="decimal" data-key="${r.key}" data-meter="${m}" value="${val}"></td><td class="${cls}">${u===''?'':u.toFixed(2)}</td>`});html+=`<td class="usage ${has&&total<0?'bad':''}">${has?total.toFixed(2):''}</td></tr>`});$('sheetTable').innerHTML=html;document.querySelectorAll('.reading').forEach(inp=>inp.addEventListener('change',e=>{setReading(e.target.dataset.key,e.target.dataset.meter,e.target.value);renderAll()}))}
function renderSummary(){const ym=$('summaryMonth').value||$('monthPicker').value;const rows=rowsForMonth(ym);let html='<tr><th>Meter</th><th>Total Usage</th><th>Average Usage / Record</th><th>Highest</th><th>Lowest</th></tr>';state.meters.forEach(m=>{const arr=rows.map((r,i)=>usageFor(ym,i,m)).filter(v=>typeof v==='number'&&v>=0);const total=arr.reduce((a,b)=>a+b,0);html+=`<tr><td>${m}</td><td>${total.toFixed(2)}</td><td>${arr.length?(total/arr.length).toFixed(2):''}</td><td>${arr.length?Math.max(...arr).toFixed(2):''}</td><td>${arr.length?Math.min(...arr).toFixed(2):''}</td></tr>`});$('summaryTable').className='summaryGrid';$('summaryTable').innerHTML=html}
function renderValidation(){const ym=$('validationMonth').value||$('monthPicker').value;const rows=rowsForMonth(ym);let issues=[];rows.forEach((r,i)=>state.meters.forEach(m=>{const cur=getReading(r.key,m);const prev=previousReading(ym,i,m);if(cur!==''&&prev!==null&&Number(cur)<prev)issues.push([prettyDate(ym,r.day),r.shift,m,prev,Number(cur),'Reading lower than previous reading'])}));if(!issues.length){$('validationTable').outerHTML='<table id="validationTable"><tr><td class="validationOk">No validation issue found for this month.</td></tr></table>';return}let html='<tr><th>Date</th><th>Shift</th><th>Meter</th><th>Previous</th><th>Current</th><th>Issue</th></tr>';issues.forEach(x=>html+=`<tr class="bad"><td>${x[0]}</td><td>${x[1]}</td><td>${x[2]}</td><td>${x[3]}</td><td>${x[4]}</td><td>${x[5]}</td></tr>`);$('validationTable').innerHTML=html}
function renderSettings(){let html='';state.meters.forEach((m,i)=>{html+=`<div class="meterItem"><input value="${m}" data-index="${i}" class="meterName"><button class="smallBtn danger" data-del="${i}">Delete</button></div>`});$('meterList').innerHTML=html;document.querySelectorAll('.meterName').forEach(inp=>inp.addEventListener('change',e=>{const i=Number(e.target.dataset.index);const old=state.meters[i];const name=e.target.value.trim();if(!name)return renderSettings();state.meters[i]=name;Object.values(state.readings).forEach(row=>{if(row[old]!==undefined){row[name]=row[old];delete row[old]}});saveState();renderAll()}));document.querySelectorAll('[data-del]').forEach(btn=>btn.addEventListener('click',e=>{const i=Number(e.target.dataset.del);const name=state.meters[i];if(!confirm(`Delete ${name}?`))return;state.meters.splice(i,1);Object.values(state.readings).forEach(row=>delete row[name]);saveState();renderAll()}))}
function renderAll(){renderSheet();renderSummary();renderValidation();renderSettings()}
document.querySelectorAll('.tab').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.tab,.panel').forEach(x=>x.classList.remove('active'));btn.classList.add('active');$(btn.dataset.tab).classList.add('active');renderAll()}));
$('addMeter').addEventListener('click',()=>{const name=$('newMeterName').value.trim();if(!name)return;if(state.meters.includes(name))return alert('Meter already exists.');state.meters.push(name);$('newMeterName').value='';saveState();renderAll()});
$('todayBtn').addEventListener('click',()=>{$('monthPicker').value=ymNow();$('summaryMonth').value=ymNow();$('validationMonth').value=ymNow();renderAll()});
$('clearMonth').addEventListener('click',()=>{const ym=$('monthPicker').value;if(!confirm(`Clear all readings for ${monthLabel(ym)}?`))return;Object.keys(state.readings).forEach(k=>{if(k.startsWith(ym))delete state.readings[k]});saveState();renderAll()});
['monthPicker','summaryMonth','validationMonth'].forEach(id=>$(id).addEventListener('change',()=>{if(id==='monthPicker'){$('summaryMonth').value=$(id).value;$('validationMonth').value=$(id).value}renderAll()}));
$('exportCsv').addEventListener('click',()=>{const ym=$('monthPicker').value;const rows=rowsForMonth(ym);const header=['Date','Shift'];state.meters.forEach(m=>header.push(`${m} Reading`,`${m} Usage`));header.push('Total Usage');const out=[['GM WATER METER REPORT'],[monthLabel(ym)],[],header];rows.forEach((r,i)=>{let total=0,has=false;const line=[prettyDate(ym,r.day),r.shift];state.meters.forEach(m=>{const val=getReading(r.key,m);const u=usageFor(ym,i,m);line.push(val,typeof u==='number'?u.toFixed(2):'');if(typeof u==='number'){total+=u;has=true}});line.push(has?total.toFixed(2):'');out.push(line)});downloadCsv(`GM_WATER_METER_REPORT_${ym}.csv`,out)});
if('serviceWorker' in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});
ensureInputs();renderAll();
